name: update the readme

on:
  issues:
    types: [opened]

jobs:
  update-my-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Process Started
        run: |
          echo "Process started"
          echo $github.event.issue.title